server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adminapp-db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user
    password: user
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: spring-admin

keycloak:
  realm: Admin-App-realm
  resource: admin-app-client
  public-client: true
  auth-server-url: http://localhost:8090/auth
  principal-attribute: name

info:
  application:
    name: admin-app
    version: '@project.version@'

logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG
